### ISSUE TITLE
图片不显示

### ISSUE THREAD

**Issue by wuenping** [xushvai/io#4]
只有《》

**Comment by xushvai** [comment]
@wuenping 啥图片？

**Comment by wuenping** [comment]
文章中插入上传的图片

**Comment by xushvai** [comment]
@wuenping 在开发环境下，上传的图片会被放到 "/data/media/adminfiles" 目录下，假设上传了文件：123.png，要在文章中使用它的话应该这么写：

```
![](media/adminfiles/123.png)
```
